server:
  port: 8080
  servlet:
    context-path: /csp
logging:
  config: classpath:logback-spring.xml
  pattern:
    console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'
  root:
   level: DEBUG